[project]
name = "tissue-segmentation"
version = "0.1.2"
description = ""
authors = [{ name = "Nick Weiss", email = "nick.weiss@mevis.fraunhofer.de" }]
requires-python = ">=3.12"
readme = "README.md"
dependencies = [
    "numpy>=2.3.5",
    "scikit-image>=0.25.2",
    "scipy>=1.16.3",
    "tensorflow-cpu>=2.20.0",
]

[dependency-groups]
dev = [
    "black>=25.11.0",
    "isort>=7.0.0",
    "pytest>=9.0.1",
]

[tool.hatch.build.targets.sdist]
include = ["tissue_segmentation"]

[tool.hatch.build.targets.wheel]
include = ["tissue_segmentation"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
